name: ProyectoDollarGo

on: 
  push:
    branches:
      - '*' # Observa cambios en cualquier rama
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: echo "Funciona Actions en cualquier rama"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run:
        npm install
        
    - name: Run Stylelint
      run:
        npx stylelint "*/.css" || true
        
    - name: Run JavaScript linter
      run:
        npm run lint:js
